### ISSUE TITLE
Welcome bot integration

### ISSUE THREAD

**Issue by Sloth-Panda** [spandey1296/ModernBanking-Management-System#7]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of SWOC. Please assign me this issue.
For reference, kindly check out: https://github.com/apps/welcome

Do add the swoc'21 and level(easy) tags to it @spandey1296

**Comment by spandey1296** [comment]
Include chatbot
